### ISSUE TITLE
Did the coveralls plugin break?

### ISSUE THREAD

**Issue by JosephMoniz** [scoverage/sbt-scoverage-samples#2]
The last commit ( 632406931a4a0a67344f74f44ff30d367b598c1d ) seemed to remove the coveralls.io build from the travis-ci script.

I've been trying to get the coveralls + scoverage plugin to run via travis but i keep getting JSON errors when i run `sbt ++$TRAVIS_SCALA_VERSION coveralls` via travis. Repro here: https://travis-ci.org/blackboxsociety/bbs-web/builds/24160041

When i run `sbt ++$TRAVIS_SCALA_VERSION scoverage:test` everything works out fine, but i don't get my coverage reports pushed to coveralls.

**Comment by BennyHill** [comment]
I would guess that this old issue is covered by other issues, eg https://github.com/scoverage/sbt-scoverage/issues/146

Could this now be closed?
